import argparse
import ast
import os
from src.pipelines.snuffy import Snuffy, Runner
import wandb
import yaml


def pretty_print(d: dict):
    print(yaml.dump(d, allow_unicode=True, default_flow_style=False))


def validate_args(args):
    args.use_mp = bool(args.use_mp)
    args.soft_average = bool(args.soft_average)
    args.for_roc_curve = (
            args.roc_run_name is not None and args.roc_run_epoch is not None
    )

    mil_dataset_to_num_feats_mapping = {
        'musk1': 166,
        'musk2': 166,
        'elephant': 230,
    }
    if args.dataset in mil_dataset_to_num_feats_mapping.keys():
        args.feats_size = mil_dataset_to_num_feats_mapping[args.dataset]
        print(f'Setting feats_size to {args.feats_size} for {args.dataset}')

    return args


def main():
    parser = argparse.ArgumentParser('Snuffy Trainer', parents=[get_args_parser()], add_help=False)
    args = parser.parse_args()
    args = validate_args(args)
    args.betas = ast.literal_eval(''.join(args.betas))  # for sweep
    args.weight_init__weight_init_i__weight_init_b = ast.literal_eval(
        ''.join(args.weight_init__weight_init_i__weight_init_b)
    )

    gpu_ids = tuple(args.gpu_index)
    os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(str(x) for x in gpu_ids)

    arch_registry = {
        'snuffy': Snuffy
    }
    try:
        trainer = arch_registry[args.arch](args)
    except KeyError as e:
        raise Exception(f'Invalid Architecture: {args.arch} | Choose from: {arch_registry.keys()}')

    if args.wandb_run is None:
        print(f'No wandb name generated by us.')

    wandb.init(
        project=f"snuffy_{args.dataset}",
        config={**vars(args)},
        mode='disabled' if args.for_roc_curve else None,
        settings=wandb.Settings(code_dir="."),
    )
    print(f'*** Run Config *** ')
    pretty_print({**vars(args)})

    runner = Runner(args, trainer)
    runner.run()
    wandb.finish()


if __name__ == '__main__':
    main()